### ISSUE TITLE
ct Bar Mode: since patch 9.1.0 (retail) Macros works no more in bar 2 

### ISSUE THREAD

**Issue by WoW-Nina** [DDCorkum/CTMod#110]
Hi since the latest patch (9.1.0) I can't activate the following macro I have in bar 2 by hotkey:

#showtooltip Himmlische Azurwolkenschlange
/wirken [button:1] Himmlische Azurwolkenschlange
/wirken [button:2] Teufelsfeuerfalke
/wirken [button:3] Mechanischer Holzextraktor

When I click on it with the mouse it works as usual, but the hotkey by keyboard does not work since the new patch.

If I put the same macro on bar 3 it works by hotkey/keyboard. 

Would be really great if that works again. Sorry for my English I am from Austria :)

Thanks in advance and best regards Nina

**Comment by DDCorkum** [comment]
Hello,

Thank you for the report.   This will be fixed in the next version of CT_BarMod.

Until then, if you add [button:31] to your macro then it will work on both mouse and keyboard. 

```
#showtooltip Himmlische Azurwolkenschlange
/wirken [button:1][button:31] Himmlische Azurwolkenschlange
/wirken [button:2] Teufelsfeuerfalke
/wirken [button:3] Mechanischer Holzextraktor
```

**Comment by WoW-Nina** [comment]
Thanks a lot. ..... With: /wirken [button:1][button:31] Himmlische Azurwolkenschlange... it works fine 

kind regards Nina
