### ISSUE TITLE
Error when opening mailbox (v9.1.0.3d dev alpha)

### ISSUE THREAD

**Issue by Agramon** [DDCorkum/CTMod#112]
Error spammed when opening mailbox (with 4 recovered items from Postmaster and Thaumaturge)

`824x CT_MailMod\CT_MailMod_MailLog.lua:330: attempt to perform arithmetic on local 'olderExpires' (a nil value)
[string "@CT_MailMod\CT_MailMod_MailLog.lua"]:330: in function <CT_MailMod\CT_MailMod_MailLog.lua:309>
[string "@CT_MailMod\CT_MailMod_MailLog.lua"]:422: in function `logFunc'
[string "@CT_MailMod\CT_MailMod_MailLog.lua"]:376: in function `logPending'
[string "@CT_MailMod\CT_MailMod_MailStructure_Incoming.lua"]:277: in function `retrieveSelectedMail'
[string "@CT_MailMod\CT_MailMod_MailStructure_Incoming.lua"]:1176: in function `action'
[string "@CT_MailMod\CT_MailMod_MailActions.lua"]:236: in function `key'
[string "@CT_MailMod\CT_MailMod-9.1.0.3.lua"]:99: in function <CT_MailMod\CT_MailMod.lua:94>

Locals:
self = <table> {
 loadMail = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:26
 filterName = <function> defined @CT_MailMod\CT_MailMod_Utility.lua:32
 actionRetrieveMail = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:1157
 getmaq = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:72
 removeMailAction = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:40
 beginProcessing = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:83
 returnSelected = <function> defined @CT_MailMod\CT_MailMod_MassOpening.lua:115
 updateMailLogButton = <function> defined @CT_MailMod\CT_MailMod_StockUI.lua:912
 getTimeFromOffset = <function> defined @CT_MailMod\CT_MailMod_Utility.lua:20
 showMailLog = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:990
 logIncoming = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:388
 cancelProcessing = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:132
 hideMailDeletePopups = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:540
 inboxUpdateMailboxCount = <function> defined @CT_MailMod\CT_MailMod_StockUI.lua:112
 updateMailLog = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:984
 downloadMail = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:1122
 convertMoneyToString = <function> defined @CT_MailMod\CT_MailMod_Utility.lua:165
 currentMailAction = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:68
 isProcessing = true
 toggleMailLog = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:1001
 pauseProcessing = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:122
 clearMailActions = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:32
 actionReturnMail = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:1185
 addMailAction = <function> defined @CT_MailMod\CT_MailMod_MailActions.lua:25
 logOutgoing = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:448
 scaleMailLog = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:1013
 externalDropDown_Initialize = <function> defined @CT_MailMod\CT_MailMod_Options.lua:368
 timeoutValue = 30
 hideOpenMailTakeItemPopups = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:794
 initOpenMail = <function> defined @CT_MailMod\CT_MailMod_OpenMail.lua:24
 zeroMailUpdater = <function> defined @CT_MailMod\CT_MailMod.lua:84
 processingEnd = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:1370
 updateMailLogColor = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:1019
 name = "CT_MailMod"
 tooMuchMail = false
 inboxUnselectSingle = <function> defined @CT_MailMod\CT_MailMod_MassOpening.lua:50
 inboxUnselectAll = <function> defined @CT_MailMod\CT_MailMod_MassOpening.lua:33
 beginIncomingAction = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:1380
 newOutgoingMail = <function> defined @CT_MailMod\CT_MailMod_MailStructure_Outgoing.lua:24
 printLogMessage = <function> defined @CT_MailMod\CT_MailMod_MailLog.lua:296
 options = <table> {
 }
 nameIsPlayer = <function> defined @CT_MailMod\CT_MailMod_Alts.lua:26
 getPlayerName = <function> defined @CT_MailMod\CT_MailMod_Utility.lua:27
 registerMailUpdater = <function> defined @CT_MailMod\CT_MailMod.lua:79
 update = <function> defined @CT_MailMod\CT_MailMod_Options.lua:213
 actionDownloadMail = <function> defined @A`

**Comment by DDCorkum** [comment]
Thank you!
