### ISSUE TITLE
Error with 2.5.2

### ISSUE THREAD

**Issue by Nerillida** [DDCorkum/CTMod#114]
Message: Interface\AddOns\CT_MapMod\CT_MapMod.lua:70: hooksecurefunc(): FlightMap_LoadUI is not a function
Time: Thu Sep  2 12:19:30 2021
Count: 1
Stack: Interface\AddOns\CT_MapMod\CT_MapMod.lua:70: hooksecurefunc(): FlightMap_LoadUI is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\CT_MapMod\CT_MapMod.lua"]:70: in function `Initialize'
[string "@Interface\AddOns\CT_MapMod\CT_MapMod.lua"]:1662: in function `update'
[string "@Interface\AddOns\CT_Library\CT_Library.lua"]:638: in function `value'
[string "@Interface\AddOns\CT_Library\CT_Library.lua"]:701: in function <Interface\AddOns\CT_Library\CT_Library.lua:697>

Locals:

**Comment by DDCorkum** [comment]
Thanks for the report.  I have a beta version ready (9.1.0.5), and I'll bump it to a full release later today after a bit more testing to make sure I'm not causing any new bugs in retail.
