### ISSUE TITLE
Leatrix Maps and CT-Mapmod

### ISSUE THREAD

**Issue by Nimbix-wow** [DDCorkum/CTMod#116]
If I have Leatrix Maps activated I cant get the "Where am I?" button to show. The CT_MapMod button is only showing at a specific size of the map, when the LeatrixMaps option "Unlock Map Frame" is activated.

**Comment by DDCorkum** [comment]
I will look into this and see if I can make it work.

Which edition are you using, just so I can trial it out on the same one?

**Comment by DDCorkum** [comment]
PS I just did a quick test on retail with Leatrix Maps 9.1.08 and CTMod 9.1.0.5; nothing seemed out of the ordinary.

**Comment by Nimbix-wow** [comment]
I use Leatrix BCC 2.5.55 and CT_MoD 9.1.0.5.

**Comment by DDCorkum** [comment]
Just found the problem.  This should be fixed in the next version.
