### ISSUE TITLE
Bug when trying to export settings

### ISSUE THREAD

**Issue by DiscordGregory** [DDCorkum/CTMod#118]
Following the steps in the 'Use Import String' tooltip I get this error 

1x CT_Library\CT_Library-9.1.0.3.lua:3822: attempt to index global 'actions' (a nil value)
[string "@CT_Library\CT_Library-9.1.0.3.lua"]:3822: in function <CT_Library\CT_Library.lua:3784>
[string "@CT_Library\CT_Library-9.1.0.3.lua"]:3882: in function <CT_Library\CT_Library.lua:3848>

Locals:
text = "=M?/E9cRV+2:e:85eIe[@S)&J83-HV?RMI`8Q77R=\W]I\]5SZ.O(3@*PJH=aMMTTYXb\\,I9=DGEbc[XDD5aU-S\>ddE+cUJe'HU=:WV\'AC3QH3)8dM8UZT\-Y@d1(W(?T<L8a`J1QGH?L<aK]McT-W9e(aRAeV@WdLcG@?KO8;KG:@:*<^89)77_CS/\,M+aE=]WPC_C]5P[RAGI*;CXIbT1QbQJUYI&GT<L`@,BC2.8^>;6W10?+?YGF.G,L>*+G77,U42:,(U;;PZ]''++4B:*:>K`7:?1_1=1\eU_JE&S08CTZE-Tc18(HKbR*[eZeSH+)\Ad[LH)Gae]=WY8Z-5^=]@,(],[]81cTGK1`0AAa6DM+Y.&E&'&/DM,+0/0^;XD+/>BJ/WPG,;*JL,*1U:*O;*V63R&1M(7FeN48.*(X_P2<*U`)RG\9CdSa[@6;?(4<E`5ad65DR_a5e9RZaaYZ4ea?TdG5@A6@6>Q'@QL[B_E\Z5C@&J:)K*41B)8-L]c0O(KDNNGe+2&b)OQ9==b/Y\5DZPJ.>8TA["
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 warning = <unnamed> {
 }
 Title = <unnamed> {
 }
 label = <unnamed> {
 }
 acceptButton = <unnamed> {
 }
 cancelButton = <unnamed> {
 }
 editBox = <unnamed> {
 }
}
(*temporary) = <userdata>
(*temporary) = <function> defined @CT_Library\CT_Library.lua:3702
(*temporary) = <function> defined @CT_Library\CT_Library.lua:3702
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 Right = <unnamed> {
 }
 Left = <unnamed> {
 }
 Middle = <unnamed> {
 }
}
(*temporary) = "attempt to index global 'actions' (a nil value)"
copyFromClipboard = <function> defined @CT_Library\CT_Library.lua:3763
lib = <table> {
 updateSlashCmd = <function> defined @CT_Library\CT_Library.lua:393
 framesAddScript = <function> defined @CT_Library\CT_Library.lua:2771
 displayTooltip = <function> defined @CT_Library\CT_Library.lua:216
 regEvent = <function> defined @CT_Library\CT_Library.lua:652
 clearTable = <function> defined @CT_Library\CT_Library.lua:137
 hash = <function> defined @CT_Library\CT_Library.lua:1394
 registerMovable = <function> defined @CT_Library\CT_Library.lua:1096
 errorformat = <function> defined @CT_Library\CT_Library.lua:177
 unblockOverflowText = <function> defined @CT_Library\CT_Library.lua:357
 framesGetData = <function> defined @CT_Library\CT_Library.lua:2731
 setSlashCmd = <function> defined @CT_Library\CT_Library.lua:381
 unschedule = <function> defined @CT_Library\CT_Library.lua:735
 setRadioButtonTextures = <function> defined @CT_Library\CT_Library.lua:1354
 displayPredefinedTooltip = <function> defined @CT_Library\CT_Library.lua:324
 compress = <function> defined @CT_Library\CT_Library.lua:1401
 copyTable = <function> defined @CT_Library\CT_Library.lua:521
 encode256To64 = <function> defined @CT_Library\CT_Library.lua:1415
 blockOverflowText = <function> defined @CT_Library\CT_Library.lua:330
 getOption = <function> defined @CT_Library\CT_Library.lua:976
 resetMovable = <function> defined @CT_Library\CT_Library.lua:1164
 print = <function> defined @CT_Library\CT_Library.lua:182
 rHGUuAb8e8m53a47KyMn3rD3NaNkaE5Qzx = <function> defined @CT_Library\CT_Library.lua:1016
 abbreviateLargeNumbers = <function> defined @CT_Library\CT_Library.lua:560
 resetOptions = <function> defined @CT_Library\CT_Library.lua:1056
 setOption = <function> defined @CT_Library\CT_Library.lua:941
 breakUpLargeNumbers = <function> defined @CT_Library\CT_Library.lua:596
 text = <table> {
 }
 framesInit = <function> defined @CT_Library\CT_Library.lua:2712
 isModuleOptionTabSelected = <function> defined @CT_Library\CT_Library.lua:3322
 framesBeginFrame = <function> defined @CT_Library\CT_Library.lua:2781
 iterateModules = <function> defined @CT_Library\CT_Library.lua:127
 version = "9.1.0.3"
 getDisplayValue = <function> defined @CT_Library\CT_Library.lua:990
 printcolor = <function> defined @CT_Library\CT_Library.lua:192
 getFrame = <function> defined @

**Comment by DDCorkum** [comment]
Thanks for the error log.  I'll look into it.

**Comment by DDCorkum** [comment]
Found the problem.  This will be fixed in the next version.

Thanks again for bringing it to my attention.
