### ISSUE TITLE
Can't delete mail with "%" symbol in "Subject"

### ISSUE THREAD

**Issue by Xdembe** [DDCorkum/CTMod#120]
version 9.1.5.1 BCC

> Message: Interface\AddOns\CT_Library\CT_Library.lua:173: invalid option in `format'
Time: Thu Feb  3 19:18:27 2022
Count: 2
Stack: Interface\AddOns\CT_Library\CT_Library.lua:173: invalid option in `format'
[string "=[C]"]: ?
[string "@Interface\AddOns\CT_Library\CT_Library.lua"]:173: in function `errorformat'
[string "@Interface\AddOns\CT_MailMod\CT_MailMod_MailLog.lua"]:310: in function `printLogMessage'
[string "@Interface\AddOns\CT_MailMod\CT_MailMod_MailStructure_Incoming.lua"]:564: in function <...Ons\CT_MailMod\CT_MailMod_MailStructure_Incoming.lua:547>
[string "@Interface\AddOns\CT_MailMod\CT_MailMod_MailStructure_Incoming.lua"]:748: in function `deleteSelectedMail'
[string "@Interface\AddOns\CT_MailMod\CT_MailMod_MailStructure_Incoming.lua"]:1232: in function `action'
[string "@Interface\AddOns\CT_MailMod\CT_MailMod_MailActions.lua"]:236: in function `key'
[string "@Interface\AddOns\CT_MailMod\CT_MailMod.lua"]:99: in function <Interface\AddOns\CT_MailMod\CT_MailMod.lua:94>
Locals: (*temporary) = "'21%', From Xdebank @ Gehennas: Deleting mail."

**Comment by DDCorkum** [comment]
Thank you for the report.

**Comment by DDCorkum** [comment]
This will be fixed in the next version, to be published in a couple days when Dragonflight 10.0.7 comes out.
