### ISSUE TITLE
CT Buff Bar Broken with ZA Patch (Classic Version)

### ISSUE THREAD

**Issue by LotG-Catherine** [DDCorkum/CTMod#121]
ZA patch, From Bug Sack:

 

51x FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
[string "@FrameXML\SecureGroupHeaders.lua"]:1026: in function <FrameXML\SecureGroupHeaders.lua:961>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:7257: in function `createBuffFrame'
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:7612: in function `createBuffFrame'
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:7627: in function `createWindow'
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:7915: in function `addWindow'
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:10280: in function <CT_BuffMod\CT_BuffMod.lua:10237>
[string "@CT_BuffMod\CT_BuffMod-9.1.0.3.lua"]:10327: in function <CT_BuffMod\CT_BuffMod.lua:10325>

Locals:
self = CT_BuffMod_AuraFrameSP1 {
0 = <userdata>
weaponButtons = <table> {
}
scriptsHooked = true
refreshTickerFunc = <function> defined @CT_BuffMod\CT_BuffMod.lua:6607
stateFrame = <unnamed> {
}
consolidatedButton = <unnamed> {
}
frameObject = <table> {
}
altFrame = <unnamed> {
}
}
filter = nil
groupBy = "HARMFUL,HELPFUL|CANCELABLE,HELPFUL|NOT_CANCELABLE"
unit = "player"
includeWeapons = 2
consolidateTo = nil
consolidateDuration = nil
consolidateThreshold = nil
consolidateFraction = nil
sortDirection = "+"
separateOwn = 0
sortMethod = <function> defined @FrameXML\SecureGroupHeaders.lua:938
time = 1179459.360000
consolidateTable = nil
weaponPosition = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
1 = "HARMFUL"
2 = "HELPFUL|CANCELABLE"
3 = "HELPFUL|NOT_CANCELABLE"
HARMFUL = 1
HELPFUL|NOT_CANCELABLE = 3
HELPFUL|CANCELABLE = 2
}
(for control) = 1
filterIndex = 1
fullFilter = "HARMFUL"
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "HARMFUL"
(*temporary) = nil
(*temporary) = <function> defined @FrameXML\SecureGroupHeaders.lua:1026
(*temporary) = "attempt to call field 'ForEachAura' (a nil value)"
tonumber = <function> defined =[C]:-1
sorters = <table> {
INDEX = <table> {
}
TIME = <table> {
}
NAME = <table> {
}
EXPIRES = <table> {
}
}
wipe = <function> defined =[C]:-1
tokenTable = <table> {
}
sortingTable = <table> {
}
groupingTable = <table> {
1 = "HARMFUL"
2 = "HELPFUL|CANCELABLE"
3 = "HELPFUL|NOT_CANCELABLE"
HARMFUL = 1
HELPFUL|NOT_CANCELABLE = 3
HELPFUL|CANCELABLE = 2
}
stripRAID = <function> defined @FrameXML\SecureGroupHeaders.lua:881
ipairs = <function> defined =[C]:-1
freshTable = <function> defined @FrameXML\SecureGroupHeaders.lua:889
max = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
configureAuras = <function> defined @FrameXML\SecureGroupHeaders.lua:735
releaseTable = <function> defined @FrameXML\SecureGroupHeaders.lua:894
tremove = <function> defined =[C]:-1

**Comment by DDCorkum** [comment]
This appears to have been due to an error in the Blizzard source that affected any addons using secure buff buttons.   Fortunately, that bug has been fixed. 

Please let me know if this is still an issue, and I will look into it further.
