### ISSUE TITLE
Dragonflight Beta support

### ISSUE THREAD

**Issue by Voxxel** [DDCorkum/CTMod#122]
Addons are now enabled in the Beta but CTMod is not working. I would really appreciate it if you could fix it anytime soon.

**Comment by DDCorkum** [comment]
I am now able to load the following modules in the Dragonflight pre-patch on the public test realm:
- CT_BuffMod
- CT_Core
- CT_ExpenseHistory
- CT_MapMod
- CT_Timer
- CT_Viewport

**Comment by Voxxel** [comment]
Looks promising! 
I can't reach the settings of Viewport because it brings up the settings of CT_Timer. Likewise Mapmod settings opens Mailmod settings and CTRA settings opens Mapmod settings. The not-yet-updated plugins cause this error and also the text overlapping bug.
I also encountered a Core bug where it seems the addon can't make chat resize buttons in any corner.

**Comment by DDCorkum** [comment]
Working on CT_UnitFrames.  I'll have to make some decisions soon concerning whether to embrace the new look, or retro, or maybe a toggle for both?


![image](https://user-images.githubusercontent.com/40327147/193420610-41809633-7403-47ff-898a-afdec5aefef5.png)

**Comment by Voxxel** [comment]
Some modernization always feels refreshing but some people rather tend to stick with retro pixels indeed. A toggle would fit all needs imo. Meanwhile, I caught a lua error :
 
```
 4x Interface/AddOns/CT_Core/CT_Core_Chat.lua:925: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:925: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:878>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:950: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:946>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:959: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:955>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:1116: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:1102>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:1152: in function `value'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:697: in function <Interface/AddOns/CT_Library/CT_Library.lua:693>

Locals:
chatFrame = ChatFrame1 {
 GatherSelectedText = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:343
 EditMode_OnResized = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:1558
 systemInfo = <table> {
 }
 OnFontObjectUpdated = <function> defined =[C]:-1
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:360
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 BaseAddMessage = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:295
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:100
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:287
 GetIndentedWordWrap = <function> defined =[C]:-1
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:425
 GetFont = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:380
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:254
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:280
 overrideFadeTimestamp = 0
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:207
 MarkDisplayDirty = <function> defined =[C]:-1
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:218
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 GetSettingValueBool = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:198
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:202
 CanEffectivelyFade = <function> defined =[C]:-1
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:44
 OnPreSizeChanged = <function> defined =[C]:-1
 dirtySettings = <table> {
 }
 GetScrollOffset = <function> defined =[C]:-1
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:236
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:227
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:330
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:171
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:132
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @Interface/FrameXML/ChatFrame.lua:2786
 InitializeFontableFrame = <function> defined =[C]:-1
 OnPostMouseDown = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 RemoveMessagesByPredicate = <function> defined =[C]
```

**Comment by DDCorkum** [comment]
I started toying with CT_BarMod to get a sense for how hard it might be.  I made some progress, but its still too soon to conclude how much more work remains to get it working.

I don't want to delay the already-updated portions of CTMod while waiting on these harder challenges, so I am going to defer that code to a future "9.2.0.3".   This means that 9.2.0.2 will exclude CT_BarMod and CT_BottomBar.

**Comment by DDCorkum** [comment]
When the Dragonflight pre-patch arrives, I now intend to retire CT_BarMod and CT_BottomBar.  I will issue a new version of CTMod coinciding with the prepatch that will simply disable these two modules in Retail (while keeping them in Classic).

However, a few things are lost that the new Dragonflight UI doesn't replace.  These niche features will be added to CT_Core, starting with the ability to drag the menu bar and bags from the bottom-right corner of the screen.

**Comment by Voxxel** [comment]
I believe there are lot of other up-to-date addons covering action bars so I don't know if so many people affected by this change. I personally use Bartender4 for all the action bar stuff and it fulfills all my need (and even beyond).

**Comment by Voxxel** [comment]
While it was working on the previous Beta build in the new build I can't use CT_Core's Movable Objectives Tracker because even if it's unlocked I can't grab the window anywhere. I can show up the border too but can't move the window. However, the "Reset window position" button is working.
I get this LUA error everytime when I toggle "Enable these options" : 

```
5x bad argument #2 to '?' (Usage: self:SetParent([parent]))
[string "=[C]"]: ?
[string "@Interface/AddOns/CT_Core/CT_Core_Other.lua"]:2413: in function <Interface/AddOns/CT_Core/CT_Core_Other.lua:2395>
[string "@Interface/AddOns/CT_Core/CT_Core_Other.lua"]:2737: in function `func'
[string "@Interface/AddOns/CT_Core/CT_Core_Other.lua"]:3208: in function `modupdate'
[string "@Interface/AddOns/CT_Core/CT_Core.lua"]:233: in function `updateFunc'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:978: in function `setOption'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:1723: in function <Interface/AddOns/CT_Library/CT_Library.lua:1718>

Locals:
```

Another bug in CT_Core: 
Can't resize chat window because even if I enable resize buttons to all corner they don't show up. The only time they're visible when I enable "Edit Mode", the new DF feature to edit the HUD, but during the Edit Mode it's not able to use CT_core's resize buttons.

I don'T get any particular LUA error for this but toggling "Show resize buttons for mouseovers only" option gives this error:

```
3x Usage: self:SetNormalTexture(asset)
[string "=[C]"]: in function `SetNormalTexture'
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:648: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:627>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:669: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:665>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:678: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:674>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:1214: in function `chatupdate'
[string "@Interface/AddOns/CT_Core/CT_Core.lua"]:234: in function `updateFunc'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:978: in function `setOption'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:1723: in function <Interface/AddOns/CT_Library/CT_Library.lua:1718>

Locals:
```

**Comment by ilmare-tuor** [comment]
"When the Dragonflight pre-patch arrives, I now intend to retire CT_BarMod and CT_BottomBar." At first this disappointed me. But, then I loaded up 9.2.0.3a into the DF beta and stated playing around. What I have found so far.

1. Voxxel's issue "I can't reach the settings of Viewport because it brings up the settings of CT_Timer. Likewise Mapmod settings opens Mailmod settings and CTRA settings opens Mapmod settings." 
 
This 1 module offset affects everything below CT_core. It is being caused by CT_ExpenseHistory failing to load (It doesn't show up in the Main Menu list). Disabling CT_ExpenseHistory before launching the game clears up this issue and all modules open correctly matching.

2. Voxxel reports problem with "CT_Core's Movable Objectives Tracker because even if it's unlocked I can't grab the window anywhere. It can show up the border too but I can't move the window. I get this LUA error everytime when I toggle "Enable these options" :"

I get the same error message. I also get the Blizz popup that CT_Core is being blocked from an action Disable or Ignore. Except for moving the window everything else seems to work. The Default UI allows you to move this window now.

more to come.

**Comment by DDCorkum** [comment]
@ilmare-tuor 

Thanks for all the feedback.   I'm definitely encouraged by the beta officially supporting ten action bars.

With this news, maybe I should look at rebuilding CT_BarMod as a slimmer module that simply enhances Edit Mode.  For example, adding in the finer adjustments like 1% scaling increments.   Whether or not this is possible will depend quite a bit on how Edit Mode actually works.  I haven't studied it in depth yet.

**Comment by ilmare-tuor** [comment]
Oops! Sorry that should have been Eight (8) action bars. A lot of people were ASKING for 10 but we got 8. Somewhere in there I confused myself ;)

Having CT_BarMod as a slimmer module for enhanced editing would be nice. The Bartender4 update supports wider ranges already but I'd hate to add a new addon just for that (and they haven't updated for the new default bars).

I'm currently running the Default bars with 8 active. On my 27", 4K display I have 2 rows of 4 bars across the bottom. 2 of the bars are set at 11 slots so they can fit with the current padding. There is a noticeable gap between buttons at padding of 2. I'm sure if I could just get a padding of 0 they would fit with all 12 buttons enabled.

So I'm running CT_Core and using that to reposition the microbar and bag bar plus these modules
CT_BuffMod
CT_Library
CT_MailMod
CT_MapMod
CT_PartyBuffs
CT_Timer
CT_UnitFrames
CT_Viewport (although I don't use it I have it enabled while testing)

Looks like you've made some updates and I will grab 9.2.0.3b and play with that.

**Comment by ilmare-tuor** [comment]
I've been playing with 9.2.0.3b and still having an issue with CT_ExpenseHistory enabled. I saw you had an update so grabbed 9.2.0.4a to see if that made an improvement. I get the same LUA error for 9.2.0.3b or 9.2.0.4a when I first log in on a character or reload the UI. Also The 1 module offset still affects everything below CT_core and CT_ExpenseHistory doesn't show up in the Main Menu list.

Page 1/5
Message: ...rface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.lua:422: hooksecurefunc(): UseContainerItem is not a function
Time: Mon Oct 17 14:24:55 2022
Count: 1
Stack: ...rface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.lua:422: hooksecurefunc(): UseContainerItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.lua"]:422: in main chunk

Locals: 

Page 2/5
Message: Interface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.lua:1 (null)
Time: Mon Oct 17 14:24:55 2022
Count: 1

Page 3/5
Message: Interface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.xml:954 Frame CT_ExpenseHistoryFrame: Unknown function CT_ExpenseHistoryFrame_OnLoad in element OnLoad
Time: Mon Oct 17 14:24:55 2022
Count: 1

Page 4/5
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.lua:1 (null)
Time: Mon Oct 17 14:24:55 2022
Count: 1

Page 5/5
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/CT_ExpenseHistory/CT_ExpenseHistory.xml:954 Frame CT_ExpenseHistoryFrame: Unknown function CT_ExpenseHistoryFrame_OnLoad in element OnLoad
Time: Mon Oct 17 14:24:55 2022
Count: 1

**Comment by DDCorkum** [comment]
Okay, I think I understand what's happening.  I heard a rumour that some bag-related API changes didn't make it yet into the public test realm -- they might be arriving in 10.0.2 but not yet in 10.0.0 which is what I've been working in.   It stands to reason this could affect CT_ExpenseHistory.

Judging from the error log, I probably need to change the hook at line 422 to something else.

**Comment by DDCorkum** [comment]
Alright.  The CT_EH problem is fixed.  I also learned a few new things about the API that I'll have to document in the wiki if they remain unchanged in a couple weeks.

**Comment by DDCorkum** [comment]
Well I didn't expect this outcome... but here is CT_BottomBar after disabling anything to do with the actual main menu bar.

![image](https://user-images.githubusercontent.com/40327147/197342697-21f62f27-15f4-4eb8-bde7-d8e6f11b5ee6.png)

**Comment by DDCorkum** [comment]
Work in progress... but coming along.   I need to figure out what happens now to the default UI with pet battles and vehicles, because that will possibly impact the bags and menu bar.

**Comment by DDCorkum** [comment]
### 10.0.0.1 (2022-10-23)
- Further updates for WoW Dragonflight
- Target health bar text on live servers with CT_UnitFrames
- Some features will be disabled (but remain in Classic) to facilitate a timely, stable release.
 
#### The WoW Dragonflight UI includes a new "edit mode" with eight movable action bars.
- CT_BarMod will disable itself automatically
- CT_BottomBar will focus on parts that Blizzard omitted
  - Bags
  - Menu buttons
  - Rep and XP bars (future version - work in progress)

#### Blizzard is preventing action bar and buff frame addons from responding to key-press and mouse-press "down" clicks.
- CT_BuffMod will remove buffs only when releasing the right mouse button
- If CT_BarMod is restored in a future version, it will be affected by the same restrictions.

**Comment by Voxxel** [comment]
Thank you very much for reviving CTmod, m8! <3
