### ISSUE TITLE
Dragonflight Beta - Tossing Errors.

### ISSUE THREAD

**Issue by greenstones** [DDCorkum/CTMod#127]
Tossing tons of errors on Dragonflight Beta.  (43 different errors.)

Maybe I am using the wrong one so let me know when the new one comes out.

**Comment by DDCorkum** [comment]
Hello,

Issue #122 follows my progress so far.  In summary, the latest beta version of 9.2.0.2 solves the most critical errors, **except for CT_BarMod and CT_BottomBar.**   I am soliciting feedback on everything else first, to get a stable build published, and in the meantime I've started some work on CT_BarMod but its not ready for anyone to test.

**Comment by DDCorkum** [comment]
### 10.0.0.1 (2022-10-23)
- Further updates for WoW Dragonflight
- Target health bar text on live servers with CT_UnitFrames
- Some features will be disabled (but remain in Classic) to facilitate a timely, stable release.
 
#### The WoW Dragonflight UI includes a new "edit mode" with eight movable action bars.
- CT_BarMod will disable itself automatically
- CT_BottomBar will focus on parts that Blizzard omitted
  - Bags
  - Menu buttons
  - Rep and XP bars (future version - work in progress)

#### Blizzard is preventing action bar and buff frame addons from responding to key-press and mouse-press "down" clicks.
- CT_BuffMod will remove buffs only when releasing the right mouse button
- If CT_BarMod is restored in a future version, it will be affected by the same restrictions.
