### ISSUE TITLE
Latest version (9.2.0.2j) partially breaks Shaman bar in WotLK Classic

### ISSUE THREAD

**Issue by robertzak** [DDCorkum/CTMod#130]
So yesterday I noticed my shaman bar was suddenly missing 2 buttons. However on reload it's working again. I will try to pay closer attention to when it's missing and when they come back. I'm not sure if something got changed from previous versions but wanted to mention it.

**Comment by DDCorkum** [comment]
If you know what was happening at the time the buttons disappear, that could also help me produce a fix.

**Comment by robertzak** [comment]
I didn't notice it today, but I wasn't on very long/looking for it. I'll try to see if it pops up again and report back. I'm hoping maybe some other LUA issue just put things in a bad state or something.

**Comment by robertzak** [comment]
No issues today. Not sure what happened yesterday. I'm going to close this as cannot reproduce. Hopefully it doesn't happen again.
