### ISSUE TITLE
Viewport for both WoTLK and Retail not functioning

### ISSUE THREAD

**Issue by PaulVlahosCS** [DDCorkum/CTMod#131]
Viewport not functioning since update 9.2.0.2j for both Retail and Classic. The previous version they function fine.

The error is:

2x CT_Viewport\CT_Viewport-9.2.0.2.lua:470: bad argument #1 to 'select' (index out of range)
[string "=[C]"]: in function `select'
[string "@CT_Viewport\CT_Viewport-9.2.0.2.lua"]:470: in function `Init'
[string "@CT_Viewport\CT_Viewport-9.2.0.2.lua"]:626: in function `update'
[string "@CT_Library\CT_Library-9.2.0.2.lua"]:634: in function `value'
[string "@CT_Library\CT_Library-9.2.0.2.lua"]:697: in function <CT_Library\CT_Library.lua:693>

**Comment by DDCorkum** [comment]
Sorry about that -- while working on some changes for Dragonflight, I goofed up the compatibility code for older versions of WoW.   I will push a beta version today that I believe solves the issue.
