### ISSUE TITLE
DragonFlight > BarMod > "Hide empty button slots" stop drag & drop from spellbook

### ISSUE THREAD

**Issue by bigrck64** [DDCorkum/CTMod#149]
Hi DDCorkum !

First, a big thanks to maintain CTMod for DragonFlight, I know it's not one easy task with all the UI changes.

I have find a new problem with 10.0.2.3d release, when I check the BarMod option "Hide empty button slots", then /reload, I can only "drag & drop" ONE spell from the spellbook to any barmod. Once this move is done, I can no more "drag & drop" any spell from spellbook to barmod.

Until fix, I have unchecked the "Hide empty button slots" barmod option, but the UI is less clean without it :)

Thanks for all !

**Comment by DDCorkum** [comment]
Thanks for the report.  This seems like it should be an easy fix; I probably need to detect the successful drag and then re-apply the workaround that I was originally using to operate the button grid.

**Comment by bigrck64** [comment]
Awesome, thanks for the quick fix :)
I tested the 10.0.2.4d following file, and it fixed the problem :

https://raw.githubusercontent.com/DDCorkum/CTMod/ba26e507f912e39bbd48a02e446f0d698b955903/CT_BarMod/CT_BarMod_Groups.lua
