### ISSUE TITLE
Bar Issues in WotLK Classic 3.4.1

### ISSUE THREAD

**Issue by robertzak** [DDCorkum/CTMod#152]
Cross-posting from curse:

It appears Wotlk Classic 3.4.1 partially broke the bars. I'm not getting LUA errors though. The standard bar with the Gryphons is showing up, and the reputation bar isn't moveable/is in the wrong spot. 
 

Also the shaman bar still appears to be broken. I had been using an older version of CTMod (10.0.2.1c) without the shaman bar error, but I tried to upgrade to the latest (10.0.2.4f) in the hopes it would handle 3.4.1 better, but it doesn't appear to.

I haven't had a chance to try to mess with it, but I can post some screen shots if that's helpful.

Thanks again for your work.

**Comment by robertzak** [comment]
Playing around a bit more.. 10.0.2.4f works better for the shaman bar. My load-outs were all broken, but once I updated them it seems to work fine. The only (minor) issue now is the totem recall button is missing

I was also able to work around the issue with the reputation bar by hiding it for now. If you uncheck the activate button for the experience bar it shows the default bar, so I left it activated but hid both bars instead.

**Comment by Airstrike1223** [comment]
I'm also seeing the same issues described by @robertzak

**Comment by robertzak** [comment]
1 LUA error I'm seeing. I'm going to try to investigate if there were changes to `ClearPointByName` when I have a few minutes..but I'm not a LUA developer..so will be mostly guess work

`
Date: 2023-01-18 14:41:59
ID: 15
Error occured in: Global
Count: 54
Message: ...rface/AddOns/CT_BottomBar/CT_BottomBar_MultiCast.lua line 39:
   attempt to call method 'ClearPointByName' (a nil value)
Debug:
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar_MultiCast.lua"]:39:
      ...rface/AddOns/CT_BottomBar/CT_BottomBar_MultiCast.lua:26
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar_MultiCast.lua"]:62: enableFunc()
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar_Addons.lua"]:384: enable()
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar_Addons.lua"]:328: init()
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar.lua"]:429:
      Interface/AddOns/CT_BottomBar/CT_BottomBar.lua:424
   [string "@Interface/AddOns/CT_BottomBar/CT_BottomBar.lua"]:808: update()
   [string "@Interface/AddOns/CT_Library/CT_Library.lua"]:634: value()
   [string "@Interface/AddOns/CT_Library/CT_Library.lua"]:697:
      Interface/AddOns/CT_Library/CT_Library.lua:693
Locals:
x = 956.201782
y = 189.033325
x2 = 281.266632
y2 = 57.600002
scale = 0.900000
x3 = 251.566635
y3 = 57.600002
(*temporary) = nil
(*temporary) = MultiCastRecallSpellButton {
 0 = <userdata>
 HotKey = MultiCastRecallSpellButtonHotKey {
 }
 NewActionTexture = Texture {
 }
 Border = MultiCastRecallSpellButtonBorder {
 }
 Flash = MultiCastRecallSpellButtonFlash {
 }
 icon = MultiCastRecallSpellButtonIcon {
 }
 AutoCastable = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 SpellHighlightTexture = Texture {
 }
 buttonType = "MULTICASTRECALLBUTTON"
 NormalTexture = MultiCastRecallSpellButtonNormalTexture {
 }
 FlyoutBorderShadow = MultiCastRecallSpellButtonFlyoutBorderShadow {
 }
 FlyoutBorder = MultiCastRecallSpellButtonFlyoutBorder {
 }
 Count = MultiCastRecallSpellButtonCount {
 }
 AutoCastShine = MultiCastRecallSpellButtonShine {
 }
 FlyoutArrow = MultiCastRecallSpellButtonFlyoutArrow {
 }
 cooldown = MultiCastRecallSpellButtonCooldown {
 }
 Name = MultiCastRecallSpellButtonName {
 }
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = "attempt to call method 'ClearPointByName' (a nil value)"
isEnabled = true
module = <table> {
 animStopped = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar.lua:133
 ctBagsBar = <table> {
 }
 hasVehicleUI = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Override.lua:27
 pendingOptions = <table> {
 }
 mainmenuConfigure = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:300
 setDelayedUpdate = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar.lua:156
 ctRelativeFrame = UIParent {
 }
 mainmenuInit = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:317
 isBlizzardAnimating = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar.lua:139
 insertAddonTitle = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:102
 rescaleMicroButtons = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Menu.lua:456
 isOverrideActionBarAnimating = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Override.lua:67
 updateBarVisibility = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Addons.lua:780
 isMainMenuBarAnimating = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:226
 showOverrideActionBar = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Override.lua:207
 configureArtwork = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:203
 hasPetBattleUI = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_PetBattle.lua:22
 updateSpecialVisibility = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Addons.lua:787
 ctVehicleBar = <table> {
 }
 ctPossess = <table> {
 }
 restoreGryphons = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:60
 hasOverrideUI = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Override.lua:37
 ctActionBarPage = <table> {
 }
 optionsInit = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:1217
 show = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:117
 hideMenuAndBagsBackground = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:168
 frame = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:664
 disableActionBar = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_MainMenu.lua:253
 CT_BottomBar_ExpBar_GetHideExperienceBar = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Exp.lua:659
 optionsInitApplied = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:1127
 updateOptionFromOutside = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Options.lua:88
 override_OnUpdate = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Override.lua:259
 update = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar.lua:645
 CT_BottomBar_RepBar_SetWidth = <function> defined @Interface/AddOns/CT_BottomBar/CT_BottomBar_Rep.lua:400
 h
AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  WowheadLooter, v30401
  Atlas, vv1.52.05
  AtlasBurningCrusade, vv1.52.01
  AtlasClassicWoW, vv1.52.01
  AtlasDungeonLocs, vv1.52.01
  AtlasTransportation, vv1.52.01
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, v@project-version@
  AtlasLootClassicData, v@project-version@
  AtlasLootClassicDungeonsAndRaids, v@project-version@
  Attune, v311
  AucAdvanced, v3.4.6831 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  AutoBarWrath, v3.00.4.07
  BankItems, v2.56
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  ClassicCastbars, vv1.5.2
  CTBarMod, v10.0.2.4
  CTBottomBar, v10.0.2.2
  CTLibrary, v10.0.2.3
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=442)
`

**Comment by robertzak** [comment]
Also seeing an issue with the Leave Vehicle button..

**Comment by robertzak** [comment]
WRT the LUA error I'm not sure if it's as simple as changing:

```
MultiCastRecallSpellButton:ClearPointByName("BOTTOMLEFT")
```

to:

```
MultiCastRecallSpellButton:ClearPoint("BOTTOMLEFT")
```

**Comment by robertzak** [comment]
That seems to have fixed all of my issues...

**Comment by DDCorkum** [comment]
Thanks for this.  I'll merge and issue something out.
