### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by FuryOK** [DDCorkum/CTMod#155]
Hi. When letter have multiple items its shows like a black square.
![image](https://user-images.githubusercontent.com/123043665/213839584-6270774b-5271-43d5-951e-7ff3f3ebcf99.png)

**Comment by DDCorkum** [comment]
Thanks for the report; I am inserting the fix, https://github.com/DDCorkum/CTMod/pull/154/commits/627cbe2191b63c3081488781d8260e5155d48ccb, to 10.0.2.5 and pushing it out this weekend.
