### ISSUE TITLE
Lua Error Alt Left Click to add item to Send Mail window 

### ISSUE THREAD

**Issue by Xdembe** [DDCorkum/CTMod#156]
*Lua Error*
CT_MailMod/CT_MailMod_SendMail.lua:34: attempt to call global 'PickupContainerItem' (a nil value)
[string "@CT_MailMod/CT_MailMod_SendMail.lua"]:34: in function `func'
[string "@CT_Core/CT_Core_Other.lua"]:1478: in function <CT_Core/CT_Core_Other.lua:1475>
[string "=[C]"]: in function `ContainerFrameItemButton_OnModifiedClick'
[string "*ContainerFrame.xml:165_OnClick"]:11: in function <[string "*ContainerFrame.xml:165_OnClick"]:1>
[string "=[C]"]: ?

**Comment by Xdembe** [comment]
change line 34 with
```
C_Container.PickupContainerItem(bag, item);
```
probably fix it

**Comment by DDCorkum** [comment]
Thanks.

For classic compatibility:

```lua
(PickupContainerItem or C_Container.PickupContainerItem)(bag, item)
```
