### ISSUE TITLE
New error in classic with latest CTMod 10.0.7.1d

### ISSUE THREAD

**Issue by Nerillida** [DDCorkum/CTMod#164]
Message: Interface\AddOns\CT_BarMod\CT_BarMod.lua:680: attempt to call global 'GetOverrideBarIndex' (a nil value)
Time: Wed Mar 22 10:31:38 2023
Count: 1
Stack: Interface\AddOns\CT_BarMod\CT_BarMod.lua:680: attempt to call global 'GetOverrideBarIndex' (a nil value)
[string "@Interface\AddOns\CT_BarMod\CT_BarMod.lua"]:680: in function <Interface\AddOns\CT_BarMod\CT_BarMod.lua:677>
[string "@Interface\AddOns\CT_BarMod\CT_BarMod.lua"]:768: in function <Interface\AddOns\CT_BarMod\CT_BarMod.lua:740>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\CT_Library\CT_Library.lua"]:965: in function `value'
[string "@Interface\AddOns\CT_Library\CT_Library.lua"]:691: in function <Interface\AddOns\CT_Library\CT_Library.lua:687>

Locals: frame = CT_BarMod_SecureFrame {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = CT_BarMod_SecureFrame {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
}
(*temporary) = "maxPage"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetOverrideBarIndex' (a nil value)"
secureFrame_OnAttributeChanged = "	-- Parameters: self, name, value
	-- self == our secure frame
	-- name == name of attribute
	-- value == value of attribute

	if name == "state-vehicleui" then
		self:SetAttribute("hasVehicleUI", value)
	elseif name == "state-overridebar" then
		self:SetAttribute("hasOverrideBar", value)
	elseif name == "state-possessbar" then
		self:SetAttribute("hasPossessBar", value)
	elseif name == "state-petbattle" then
		self:SetAttribute("hasPetBattle", value)
	elseif name == "state-dragonriding" then
		self:SetAttribute("hasDragonRiding", value)
	end

	if (name == "state-overridebar" or name == "state-vehicleui" or name == "state-possessbar" or name == "state-dragonriding") then
		-- Override bar, vehicle bar, or possess bar state has changed.
		--
		-- Update visibility of buttons with related action ids.
		--
		-- If the user has configured a bar to always show the control bar buttons,
		-- when the buttons on the control bar no longer have actions (such as after
		-- exiting a vesecureFrame_OnAttributeChanged_unsecure = <function> defined @Interface\AddOns\CT_BarMod\CT_BarMod.lua:520
secureFrame_updateButton_unsecure = <function> defined @Interface\AddOns\CT_BarMod\CT_BarMod.lua:509
initUpdateButtonType = <function> defined @Interface\AddOns\CT_BarMod\CT_BarMod.lua:419

Reverted to previous.

**Comment by DDCorkum** [comment]
Thanks for the report.  I am pushing out a quick fix shortly.

**Comment by DDCorkum** [comment]
Okay, sorry about that.  10.0.7.2 should have it working again.   Please let me know if you still encounter issues.
