### ISSUE TITLE
CT Bars broken since update this morning

### ISSUE THREAD

**Issue by Zefflin** [DDCorkum/CTMod#165]
The addon has issues with showing the bars on WoW Classic since the latest update on curseforge. I had to revert to Blizzard bars.

**Comment by DDCorkum** [comment]
Okay, sorry about that.  10.0.7.2 should have it working again.   Please let me know if you still encounter issues.

**Comment by Zefflin** [comment]
Works like a charm. Thank you :)

	-----------------------------------------From: "Dahk Celes" 
To: "DDCorkum/CTMod"
Cc: "Zefflin", "Author"
Sent: Wednesday March 22 2023 3:53:37PM
Subject: Re: [DDCorkum/CTMod] CT Bars broken since update this morning
(Issue #165)

	Okay, sorry about that. 10.0.7.2 should have it working again. Please
let me know if you still encounter issues. 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/DDCorkum/CTMod/issues/165#issuecomment-1480174659
[2]
