### ISSUE TITLE
Issues with WotLK 3.4.2

### ISSUE THREAD

**Issue by robertzak** [DDCorkum/CTMod#167]
I'm getting an error when I log in from a library that looks be used by CTMod. I've been waiting for an update, but when I looked at the comments and the Issues on here, it didn't seem like anyone has reported it yet.

```
Date: 2023-06-30 16:27:11
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/CT_Library/Libs/TaintLess...."] line 77:
   hooksecurefunc(): GetAttribute is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "Interface/AddOns/CT_Library/Libs/TaintLess.xml:<Scripts>"]:77: in main chunk
```

**Comment by DDCorkum** [comment]
Thanks for the report.

A quick glance at TaintLess and it appears a fix is already available.  I will incorporate it into CTMod shortly.

https://www.townlong-yak.com/addons/taintless/release/23-05-18

**Comment by robertzak** [comment]
awesome. tyvm!
