### ISSUE TITLE
Since patch I keep getting

### ISSUE THREAD

**Issue by Msthea** [DDCorkum/CTMod#170]
Message: Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:830: attempt to index field 'animOut' (a nil value)
Time: Wed Jul 12 11:31:54 2023
Count: 1
Stack: Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:830: attempt to index field 'animOut' (a nil value)
[string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:830: in function <Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:815>
[string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:865: in function <Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:853>
[string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:914: in function `?'
[string "@Interface/AddOns/CT_BarMod/CT_BarMod_ActionButton.lua"]:651: in function `showOverlayGlow'
[string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:1719: in function `eventFuncs'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:694: in function <Interface/AddOns/CT_Library/CT_Library.lua:687>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: overlay = CT_BarMod__ActionButtonOverlay36 {
 0 = <userdata>
 ProcLoop = AnimationGroup {
 }
 OnHide = <function> defined @Interface/FrameXML/ActionButton.lua:904
 ProcStartAnim = AnimationGroup {
 }
 ProcLoopFlipbook = Texture {
 }
 ProcStartFlipbook = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "OnHide"
(*temporary) = <function> defined @Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:823
(*temporary) = 181662
(*temporary) = "attempt to index field 'animOut' (a nil value)"
tremove = <function> defined =[C]:-1
unusedOverlayGlows = <table> {
}
numOverlays = 36
CT_BarMod__ActionButton_OverlayGlowAnimOutFinished = <function> defined @Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:806

**Comment by DDCorkum** [comment]
In 10.1.5.1a beta, I am disabling the overlay glow which appears when you have an enhanced or free use of an ability.   I can probably restore this feature, but at least this is an interim solution to make the errors go away.

**Comment by Aciddeathx** [comment]
Thank you for the interim update, hoping you can fix the glow at some point!

**Comment by Sillysith** [comment]
Where is the overlay mode? I want to disable it on mine too.

**Comment by DDCorkum** [comment]
Fixed by #172 (thank you dratr) and the feature is now restored in 10.2.0.1
