### ISSUE TITLE
AddOn 'CT_UnitFrames' tried to call the protected function 'StatusBar:Show()'.

### ISSUE THREAD

**Issue by Aciddeathx** [DDCorkum/CTMod#173]
Started getting these errors today in live

[ADDON_ACTION_BLOCKED] AddOn 'CT_UnitFrames' tried to call the protected function 'StatusBar:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@CT_UnitFrames/CT_UnitFrames.lua"]:143: in function `UpdateStatusBarTextString'
[string "@CT_UnitFrames/CT_PlayerFrame.lua"]:27: in function <CT_UnitFrames/CT_PlayerFrame.lua:25>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetValue'
[string "@FrameXML/UnitFrame.lua"]:1009: in function <FrameXML/UnitFrame.lua:989>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

I assume it has something to do with the Scorpio addon?

 [ADDON_ACTION_BLOCKED] AddOn 'Scorpio' tried to call the protected function 'StatusBar:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@FrameXML/TargetFrame.lua"]:379: in function `CheckClassification'
[string "@FrameXML/TargetFrame.lua"]:138: in function `Update'
[string "@FrameXML/TargetFrame.lua"]:162: in function `OnEvent'
[string "@FrameXML/UnitFrame.lua"]:1072: in function <FrameXML/UnitFrame.lua:1070>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by ilmare-tuor** [comment]
Having the same issue
