### ISSUE TITLE
CT BarMod un Classic error - UpdateHotkeys is not a function

### ISSUE THREAD

**Issue by Nerillida** [DDCorkum/CTMod#176]
WoW Classic 1.15.0 (52186)

Date: 2023-11-15 13:59:36
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua line 1975:
   hooksecurefunc(): UpdateHotkeys is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:1975: in main chunk
Locals:

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BadBoy, vv10.2.0
  BadBoyCCleaner, vv10.2.0
  BadBoyIgnore, vv10.2.0
  BasicChatMods, vv10.2.0
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  BetterVendorPrice, vv1.19.04
  CTBarMod, v10.1.7.1
  CTLibrary, v10.1.0.2
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  BlizRuntimeLib v1.15.0.52186(EU) <enUS>
  (ck=2fb)

**Comment by DDCorkum** [comment]
Got it, thanks!  Will be fixed in a few moments.

**Comment by Nerillida** [comment]
Thanls
