### ISSUE TITLE
CT_MailMod, net income does not shows in Classic game versions

### ISSUE THREAD

**Issue by Xdembe** [DDCorkum/CTMod#186]
CTMod 10.2.5.1d
GameVer 1.15.1 and 3.4.3
MAIL_CLOSED event was replaced with PLAYER_INTERACTION_MANAGER_FRAME_HIDE so line does not working anymore
https://github.com/DDCorkum/CTMod/blob/3250f67a36398d0db5c6ad1eb219e82aebff452a/CT_MailMod/CT_MailMod.lua#L175C20-L175C31

**Comment by DDCorkum** [comment]
Thank you.  Including this in the next update.
