### ISSUE TITLE
CT_Bottom Bar moves my menu bar and cannot be shifted

### ISSUE THREAD

**Issue by DavePNZ** [DDCorkum/CTMod#188]
After upgrade to Cata - my menu bar locates in the middle of my screen, 
![Screenshot 2024-05-12](https://github.com/DDCorkum/CTMod/assets/169588210/6e80453f-bb0d-48e4-b55c-7911fe256a6a)

I have identified CTBottomBar as being the issue - when I disable it, the bar reverts back to normal. I cannot shift it or restore otherwise using any of the settings in CTBottombar

**Comment by robertzak** [comment]
I think I have a fix for CTBottomBar. at least it's mostly working for me now. 

If you replace every instance (there are several) of `ReputationWatchBar_UpdateMaxLevel` with `ReputationWatchBar_Update` things sees mostly better. Still a work in progress though, and I'm not a lua/wow mod developer so I'm mostly just doing stuff with trial and error

**Comment by robertzak** [comment]
I released a "fixed" version for cata classic you can download: https://github.com/robertzak/CTMod/archive/refs/tags/4.4.0_cata_classic_fix.zip

**Comment by ablib2** [comment]
So far this looks really good.  Huge thanks.  I get the following error when a spell procs that lights up the taskbar:

Date: 2024-05-12 21:48:50
ID: 1
Error occured in: Global
Count: 3
Message: Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua line 868:
   attempt to index field 'ProcStartAnim' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:868:
      Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua:838
   [string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:899: ?()
   [string "@Interface/AddOns/CT_BarMod/CT_BarMod_ActionButton.lua"]:651: showOverlayGlow()
   [string "@Interface/AddOns/CT_BarMod/CT_BarMod_Use.lua"]:1704: eventFuncs()
   [string "@Interface/AddOns/CT_Library/CT_Library.lua"]:694:
      Interface/AddOns/CT_Library/CT_Library.lua:687
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by robertzak** [comment]
I can try to take a look after work, but I don't have much time. I may not be able to spend much on it until the weekend.

Can you provide more specifics? What spell/class caused this? Was it a proc or something?

Being able to recreate it locally will be important for me to try to test any fix (assuming I can come up with one)

**Comment by DavePNZ** [comment]
So I have two Mages... and it happens on both. It started only after the
Cata upgrade. I identified it by disabling all add-ons and enabling one at
a time. It only occurred when I enabled CTBottom Bar. The workaround is
that because CTBottom Bar doesn't really effect game play, is to leave it
disabled. It appears that some reason CTBottom Bar is causing a change in
the location coordinates of the menu bar. Deactivating and hiding the menu
bar in CTBottom Bar just causes the bar in mid screen to disappear. It does
not cause the Bar to appear in its default position. Also, I have no
ability to drag the bar at all so I can't just drag it back into the right
position.

**Comment by DavePNZ** [comment]
Just a thought, I assume there is code in CT that relates to the
positioning of the menu bar. If you can let me know where and what it
should be, I can try and compare it to what I have.  The other option is to
delete CTMod altogether and reinstall in the event it is the result of a
corruption.

**Comment by robertzak** [comment]
This was directed at @ablib2 .

Did you try the zip file I linked @DavePNZ ? That should fix your original problem, or at least it has for me. I didn't log into my mage though

**Comment by ablib2** [comment]
My specific issue was when Impact or Hot Streak procs.  This is in the Cata pre-patch, btw.

When these proc, the bar should light up, but instead this error happens, and the bars do nothing.

**Comment by robertzak** [comment]
@ablib2 I think I fixed it (and another lua error I ran into when I logged onto my mage).

Give it a try when you have a chance and let me know: https://github.com/robertzak/CTMod/archive/refs/tags/10.3.0.1.zip

**Comment by DavePNZ** [comment]
Rob.... I uploaded the new CTBottomBar folder and replaced all of the
existing files.... Works perfect 👌

**Comment by ablib2** [comment]
> @ablib2 I think I fixed it (and another lua error I ran into when I logged onto my mage).
> 
> Give it a try when you have a chance and let me know: https://github.com/robertzak/CTMod/archive/refs/tags/10.3.0.1.zip

So far so good.  You're amazing!
