### ISSUE TITLE
Will not even work with today's patch

### ISSUE THREAD

**Issue by Msthea** [DDCorkum/CTMod#193]
Defaults to standard Blizzard. Can not even open CT_Mod in WoW.
![Uploading Screenshot 2024-08-13 173307.png…]()

**Comment by ilmare-tuor** [comment]
Hear to confirm I'm having the same behavior

**Comment by zealvurte** [comment]
A non-exhaustive list of issues:
- TaintLess needs to be updated.
- `GetAddOnMetadata` needs to be replaced with `C_AddOns.GetAddOnMetadata`.
- `GetNumSpellTabs` needs to be replaced with `C_SpellBook.GetNumSpellBookSkillLines`.
- `GetSpellTabInfo` needs to be replaced with `C_SpellBook.GetSpellBookSkillLineInfo` and the calls reworked for the new function signature.
- `GetSpellBookItemName` needs to be replaced with `C_SpellBook.GetSpellBookItemName` and the calls reworked for the new function signature.
- `UnitAura` needs to be replaced with `C_UnitAuras.GetAuraDataByIndex` and reworked for the new function signature.

**Comment by Voxxel** [comment]
zealvurte, could you elaborate, where should I replace these things. In which files, I mean. I use CT_Core + CT_Library (mandatory) and the CT_Buff mod only.

**Comment by Hentaya** [comment]
Voxxel, back it up, turn off updates for now, and then use a tool like GrepWin against your Interface director to search and replace. Otherwise, get BugGrabber and BugSack, and replace the occurrences it finds until you get no errors.

ct_Buff is gonna have some issues with new auras as well.

The basic issue is that Blizzard has wiped pretty much all the 'deprecated' code since 10.0.0 in one fell swoop, and any devs who weren't already supporting 'pre' and 'post' usage in the code, broke.

**Comment by Pred147** [comment]
Hey, when will there be an update?

CTmod Addon is almost dead, I mean it cannot load and all my action bars are disappeared since the latest patch from Blizz.
Please please, fix it as soon as possible. :-)

**Comment by ilmare-tuor** [comment]
Pred147, Did you read any of the above comments? There is significant work to get an update out. You need to have some patients considering it is free and maintained by volunteer(s).

In the meantime go into Options/Action bars, turn on the default bars and use the built in UI for awhile. Not quite as good as CT_Mod but has gotten much closer.

**Comment by DDCorkum** [comment]
An update is forthcoming, to resolve issues that were apparent when first logging on.

**Comment by Cassafrass70** [comment]
Just wanted to say thank you for your hard work. I've used this addon for a long time and I really like it.
