### ISSUE TITLE
No access to options menus

### ISSUE THREAD

**Issue by shallowmonk** [DDCorkum/CTMod#197]
addon is/are listed but cannot use the click button drop down menu under the calendar or manually type the "/ct_____ " to gain access to the options. after last maintenance I did do a scan and repair if that may be causing a specific problem on my end if no one else has encountered this issue.

**Comment by DDCorkum** [comment]
Thank you for the report.  The root cause was that Blizzard changed the name of a function which had been around since Vanilla, and every single component of CTMod depended on this function near the top of the program.

Things should be better in 11.0.2.3 which I am now distributing.
