### ISSUE TITLE
CT PartyBuffs - attempt to compare number with nil

### ISSUE THREAD

**Issue by mmofanatic90210** [DDCorkum/CTMod#198]
Latest build, here's everything from one of the lua dumps.
I only run Core, Library, Party, Mail

Message: Interface/AddOns/CT_PartyBuffs/CT_PartyBuffs.lua:186: attempt to compare number with nil
Time: Sun Aug 18 16:27:24 2024
Count: 46
Stack: Interface/AddOns/CT_PartyBuffs/CT_PartyBuffs.lua:186: attempt to compare number with nil
[string "@Interface/AddOns/CT_PartyBuffs/CT_PartyBuffs.lua"]:186: in function <Interface/AddOns/CT_PartyBuffs/CT_PartyBuffs.lua:178>

Locals: (for state) = <table> {
  = true
}
(for control) = CT_PartyBuffFrame1 {
 buffs = <table> {
 }
 debuffs = <table> {
 }
 unit = "party1"
}
frame = CT_PartyBuffFrame1 {
 buffs = <table> {
 }
 debuffs = <table> {
 }
 unit = "party1"
}
debuffsShown = 0
(for state) = <table> {
 1 = Button {
 }
 2 = Button {
 }
 3 = Button {
 }
 4 = Button {
 }
 5 = Button {
 }
 6 = Button {
 }
}
(for control) = 1
i = 1
button = Button {
 Count = FontString {
 }
 id = 1
 Border = Texture {
 }
 Icon = Texture {
 }
 unit = "party1"
}
aura = <table> {
 spellId = 373693
 isBossAura = false
 duration = 6
 expirationTime = 238457.700000
 isFromPlayerOrPlayerPet = false
 points = <table> {
 }
 icon = 135265
 nameplateShowPersonal = false
 nameplateShowAll = false
 auraInstanceID = 25882
 timeMod = 1
 isRaid = false
 isHarmful = true
 canApplyAura = false
 name = "Living Bomb"
 isHelpful = false
 applications = 0
 isNameplateOnly = false
 isStealable = false
}
(*temporary) = FontString {
}
(*temporary) = nil
(*temporary) = true
(*temporary) = <table> {
 spellId = 373693
 isBossAura = false
 duration = 6
 expirationTime = 238457.700000
 isFromPlayerOrPlayerPet = false
 points = <table> {
 }
 icon = 135265
 nameplateShowPersonal = false
 nameplateShowAll = false
 auraInstanceID = 25882
 timeMod = 1
 isRaid = false
 isHarmful = true
 canApplyAura = false
 name = "Living Bomb"
 isHelpful = false
 applications = 0
 isNameplateOnly = false
 isStealable = false
}
(*temporary) = "points"
(*temporary) = "attempt to compare number with nil"
triggers = <table> {
  = true
}
debuffFilter = "HARMFUL"
layout = 1
buffFilter = "HELPFUL"

**Comment by DDCorkum** [comment]
Thank you for the report.  Addressed in 11.0.2.3
