### ISSUE TITLE
Buff Bar Not Cleaning up Expired Buffs/Auras in WoW Classic

### ISSUE THREAD

**Issue by robertzak** [DDCorkum/CTMod#63]
I play a Shaman in WoW Classic and ever since the last Classic update the buff bar seems to have issues with expired buffs. This is most noticeable with my totems. They last for 1-2 minutes and I get an an aura when in range of them.

In the past when the totems despawned the aura would drop off the Buff mod, but that no longer seems to occur.

I think normal buffs are turning to a black square when they expire. However, I haven't played in a few days so that may not be right. 

I'm not getting any LUA errors, it just doesn't seem to be updating properly.

I can try to take some screen shots this weekend when I play again if that's helpful. I mostly came to see if there as an existing Bug report, but it doesn't appear to be so I thought I should submit something before I forget again.

**Comment by DDCorkum** [comment]
Thanks for the report.  Two people on the curseforge website said they had an issue with classic CT_BuffMod as well, but I haven't been able to figure it out.

Do you only get this in situations when there are lots of other buffs?  I stood in a corner of an inn with my lvl 37 mage, with three buffs and casting blink repeatedly (a 2-second buff), and I don't see anything unusual.

**Comment by robertzak** [comment]
I want to say yes, since I mostly raid. I'm running BWL shortly, I'll try to keep an eye on to help with debugging it and hopefully snag some screen shots if I remember that I can post sometime tomorrow.

**Comment by robertzak** [comment]
and so far tonight it's not been happening. Go figure...

**Comment by DDCorkum** [comment]
Some possibilities I can think of:
- It requires a minimum number of buffs to occur
- It requires certain kinds of buffs to be active
- It requires certain kinds of gear or gear enhancements to be active

The latter two would explain why it started happening in the recent patch.

**Comment by robertzak** [comment]
It's possible the totems aura weren't dropping off when they should tonight but everytime I check it seemed to be working and I didn't see any black boxes like last week.

The more I think about it the more I think it starting happening with the phase 5 patch, not the last mod update. Especially since I looked at your changelog and the last update didn't include the Buff mod.

I had most world buffs, DMN buffs, totems and food buffs tonight, so I'm not really sure what the difference was. I saw it during both Molten Core and BWL last week. We don't bother with DMN for MC runs so that was 3 fewer buffs then.

I have another raid on Sunday and I may be running a bunch of dungeons next week, if I notice it again I'll try to get some screen shots.

If not, maybe just close this as "can't reproduce".

**Comment by DDCorkum** [comment]
I do think it relates to phase 5, because you are the third person to suggest something happened since then.  And no one has said anything on Retail.

It's always possible Blizzard fixed something behind the scenes, but I would want to wait a few weeks before jumping to that conclusion.

**Comment by DDCorkum** [comment]
An idea just hit me.  Is it possible you are now bumping up to the maximum number of permissible buffs in classic?  I have no idea what impact that might cause, since CT_BuffMod is programmed to work until up to 40 buffs but Classic starts dropping them at 32.  (32 includes certain kinds of temporary weapon enchants and stances)

**Comment by robertzak** [comment]
I don't think it's that. Our tanks regularly run into the max buff issue when fully world buffed, but I don't typically get anywhere close myself.

Quick math says: 14-15 total? 5 class buffs: (fort, spirit, mark, int, shout) + 3 DM Buffs + 2-3 World Buffs (ZG, Ony/Nef, Thrall) + 3 totems (earth, air, water) + food.

I don't typically use elixirs or a flask except during progression and even if I did that's still well below 32.

**Comment by robertzak** [comment]
So no issues again tonight. I'm going to mark this as closed. Maybe there was some kind of issue on blizzard's end that they changed/fixed after the phase 5 patch.
