### ISSUE TITLE
Stance bar moving when CTMod enabled

### ISSUE THREAD

**Issue by Smekolini** [DDCorkum/CTMod#72]
Hello

When I have CT BarMod enabled, my stance bar is moved way above my action bars, like in this picure: https://i.imgur.com/3NT1vMU.png

When i disable BarMod it looks like this: https://i.imgur.com/hApaMH1.png

I havent found a way to move the stance bar in the addon

**Comment by DDCorkum** [comment]
Good evening,

Do you also use CT_BottomBar?   It will affect the stance bar.

It is quite possible that I need to change how CT_BarMod behaves when CT_BottomBar is not installed.

**Comment by Smekolini** [comment]
Hey

I dont use CT_BottomBar, no.

**Comment by DDCorkum** [comment]
About 15% of the way down the CT_BarMod options, there is a heading "Shifting other UI elements".

At the bottom of this section, you will find a checkbox "Shift the default class bar up".   I think you need to uncheck this option and it will work how you want it to.

**Comment by DDCorkum** [comment]
Good day,

Just to follow up, did turning on that option solve your problem?


I am thinking of reworking the options menu to make it less clunky in the future, but I want to be sure you aren't stuck in the meantime with something that isn't working quite right.
