### ISSUE TITLE
CT_Core's "Movable Objectives Tracker" failure

### ISSUE THREAD

**Issue by Voxxel** [DDCorkum/CTMod#73]
When moving the quest Objectives Tracker window to another location of the screen it will reset back to the stock position in a few seconds while doing various activities. Switching off then back on the "Enable these options" button makes the objective tracker to move to the desired location again, but only for a few seconds again, then it resets back automatically.

This was a bug during the whole BFA I believe but I was not worried about it because MoveAnything was able to keep the objectives window on the left side of my screen, but in 9.0 MoveAnything doesn't work and causes massive lag, so I have to recline upon CT.

**Comment by DDCorkum** [comment]
I discovered a flaw on line 2062 of CT_Core_Other.lua -- which could result in an error message saying something like "arithmetic with a nil value"

I do not know if this fixes your problem, but I am including at least this small correction in 9.0.1.2
