### ISSUE TITLE
Display macro names > Option doesnt work

### ISSUE THREAD

**Issue by haveagwoit** [DDCorkum/CTMod#76]
After every login or reload, i can see the macro names. Only if i put the cursor on the macro, the names disappear. If i use a spell or any macro the name of the macro comes back.

I`m using the standart blizzard action buttons.

All in all the function: <"blizzard action buttons - Apply the `Display macro names` option"> doesnt work any more since the last few updates.

**Comment by DDCorkum** [comment]
Thank you for the report!   I jumped onto classic, and was able to reproduce a lot of this weirdness.  It should be possible to fix.

**Steps to reproduce:**
- In Classic, the name is is not removed from default Blizzard frames after /reload until the mouse cursor hovers over.
- In Classic, the name reappears on default Blizzard frames whenever a macro-conditional changes target

**Comment by DDCorkum** [comment]
I am uploading an experimental fix to Curse.  It is still an alpha version, and will be part of 9.0.1.2 once released.
