### ISSUE TITLE
CT_UnitFrame taint.log entry.

### ISSUE THREAD

**Issue by Wyebert** [DDCorkum/CTMod#78]
Entry in taint.log believe related to CT_UnitFrames.  Appears when playing Windwalker, possibly related to using Storm, Earth and Fire.

11/5 01:07:16.636  Interface\FrameXML\TextStatusBar.lua:54 TextStatusBar_UpdateTextStringWithValues()
11/5 01:07:16.636  An action was blocked in combat because of taint from CT_UnitFrames - PetFrame:SetPoint()
11/5 01:07:16.636      Interface\FrameXML\PetFrame.lua:56 PetFrame_UpdateAnchoring()
11/5 01:07:16.636      Interface\FrameXML\PetFrame.lua:85 PetFrame_Update()
11/5 01:07:16.636      PetFrame:OnShow()
11/5 01:07:16.636      PetFrame:Show()
11/5 01:07:16.636      Interface\FrameXML\PetFrame.lua:67 PetFrame_Update()
11/5 01:07:16.636      Interface\FrameXML\PetFrame.lua:103 OnEvent()
11/5 01:07:16.636      Interface\FrameXML\UnitFrame.lua:921

**Comment by DDCorkum** [comment]
Thank you for this entry.

I will ask my family members with various pet classes to keep an eye.

**Comment by DDCorkum** [comment]
#82 possibly resolves this issue -- but I will be testing further before distributing a beta version.

**Comment by DDCorkum** [comment]
I will close this ticket, but continue to monitor in the background for other possible sources of taint because I am not convinced that #82 completely solves the problem.
