### ISSUE TITLE
New Ore & herb icons for MapMod

### ISSUE THREAD

**Issue by Dynaletik** [DDCorkum/CTMod#85]
Lots of herbs and ore have got old icons on the map. Is it possible to add icons (I to not know where to get the .tga files from) for these? Thanks

**Comment by DDCorkum** [comment]
Agreed... I will start assembling tga files now.

It occurs to me that death blossom appears randomly in all four zones, seemingly in the same places as the other four herbs.   I'm thinking of removing it and just converting all nodes to the four zone herbs (plus nightshade in the maw).

Does that make sense to you?

**Comment by Dynaletik** [comment]
Yes, I think that death blossom for herbs is the same as Laestrit for ore. It spawns in all of the four zones except the maw. Nightshade is a rare spawn in the four zones, too. I think it spawns in the same locations as the zone specific ore.

**Comment by DDCorkum** [comment]
![Herb_Marrowroot](https://user-images.githubusercontent.com/40327147/104852645-ca3f2380-58c1-11eb-81b7-71c87c71f71b.png)

**Comment by Dynaletik** [comment]
The marrowroot one looks litte different to
https://www.wowhead.com/item=168589/marrowroot

**Comment by Dynaletik** [comment]
All the other icons look fine, thanks for the update, just had a look.
