### ISSUE TITLE
arheiuhk_bd.TTF misssing

### ISSUE THREAD

**Issue by Nerillida** [DDCorkum/CTMod#95]
Repeatable error message

Message: Font <unnamed>: Unable to load font file Fonts\arheiuhk_bd.TTF
Time: Sun Mar 14 23:48:30 2021
Count: 4

Searching addons folder, I can only find this in one of your xml files.

**Comment by DDCorkum** [comment]
Comparison of CT_BuffMod to the Blizzard code in https://www.townlong-yak.com/framexml/live/SharedFonts.xml


**CT_BuffMod:**

```
	<FontFamily name="CT_BuffMod_NumberFont_Shadow_Med2" virtual="true">
		<Member alphabet="traditionalchinese">
			<Font font="Fonts\arheiuhk_bd.TTF" height="16">
				<Shadow>
					<Offset>
						<AbsDimension x="1" y="-1"/>
					</Offset>
				</Shadow>
			</Font>
		</Member>
	</FontFamily>
```


**Blizzard FrameXML:**

```
  <FontFamily name="NumberFont_Shadow_Med" virtual="true">
    <Member alphabet="traditionalchinese">
      <Font font="Fonts\arheiuhk_bd.TTF" height="14">
        <Shadow>
          <Offset>
            <AbsDimension x="1" y="-1"/>
          </Offset>
          <Color r="0" g="0" b="0"/>
        </Shadow>
      </Font>
    </Member>
  </FontFamily>
```

**Comment by DDCorkum** [comment]
I am downloading the 繁體中文 version of the game client, to see if I can reproduce this error.

**Comment by Nerillida** [comment]
Thanks for looking at this, it's beyond my ability to really understand.

**Comment by DDCorkum** [comment]
The code says "if using traditional chinese, use Fonts\arheiuhk_bd.TTF"

I normally use english and french, which has different fonts entirely.

**Comment by Nerillida** [comment]
I use English, no idea where the error came from. :(

**Comment by DDCorkum** [comment]
Hmm.... well now that is truly strange.  English should be using "Fonts\ARIALN.TTF" 

```
	<FontFamily name="CT_BuffMod_NumberFont_Shadow_Med2" virtual="true">
		<Member alphabet="roman">
			<Font font="Fonts\ARIALN.TTF" height="16">
				<Shadow>
					<Offset>
						<AbsDimension x="1" y="-1"/>
					</Offset>
        			</Shadow>
      			</Font>
   		</Member>
```

**Comment by DDCorkum** [comment]
It beats me why this error is happening, but I will put together an alternative solution that should safely eliminate the problem.

**Comment by Nerillida** [comment]
Very grateful

**Comment by DDCorkum** [comment]
[CT_BuffMod.zip](https://github.com/DDCorkum/CTMod/files/6138361/CT_BuffMod.zip)

Here is a new version of CT_BuffMod to try.  It delays creating a custom font until after the game is more fully loaded.

**Comment by Nerillida** [comment]
Thanks, I will use it when I restart WoW in a few hours. Again grateful.

**Comment by Nerillida** [comment]
Weoks fine. Thanks.
