### ISSUE TITLE
Typeface distortion

### ISSUE THREAD

**Issue by Nerillida** [DDCorkum/CTMod#96]
You recently made some changes regarding my issue #95

Since I downloaded the update, much of the text in chat is clipped along its lower aspect (I use 16 Font Size)
Also much text in dialog boxes is distorted, partially shaded (difficult to describe).
![Screen Shot 2021-03-29 at 16 37 24](https://user-images.githubusercontent.com/55858788/112861898-233eeb00-90ad-11eb-8c23-52db0a27d0fb.png)
The bid price is 11 
![Screen Shot 2021-03-29 at 16 39 51](https://user-images.githubusercontent.com/55858788/112862187-6bf6a400-90ad-11eb-84aa-9dc5e8e67baf.png)
See warrior in the above clip, and clipping of reasonable.

If I revert to the previous version, apart from the error, all seems good.
Sorry.

**Comment by Nerillida** [comment]
Dump: value=ChatFontNormal:GetFont()
[1]="Fonts\\ARIALN.TTF",
[2]=14,
[3]=""

Dump: value=GameFontNormal:GetFont()
[1]="Fonts\\FRIZQT__.TTF",
[2]=12.000000953674,
[3]=""

I did a repair on my WoW installation
Running under macOS 10.13.6 
Thanks again.

**Comment by DDCorkum** [comment]
Could you make a brand new toon, avoid changing any settings in CT_BuffMod, and just run into a major city to see if you get this corruption in the trade channel? 

(Alternatively: go to "Settings Import" and delete the CT_BuffMod settings on any existing toon who is already in a city -- you can then re-import the settings after from another toon.)

I am curious if CT_BuffMod is behaving differently on new vs. existing characters (ie, a character with no settings versus one with a history of different settings).

**Comment by Nerillida** [comment]
Reinstalled the latest version
New character, my usual addons, no changes made.
Both the mentioned problems are gone.

Loaded an old character, the problems are ALSO gone on the three that I tested,

The only recent changes to my addons is an update of AdvancedInterfaceOptions - which I have not ever really used.

Thanks again.

**Comment by DDCorkum** [comment]
Perfect.  If the problem reoccurs, let me know.

**Comment by Nerillida** [comment]
Grateful for your rime.
