### ISSUE TITLE
XP bar bug /CT_BottomBar

### ISSUE THREAD

**Issue by ours1011** [DDCorkum/CTMod#99]
Since the last update (9.0.5.3 SL on retail), the XP bar pops up on the top left corner of the screen for no reason while playing. (it's not there when logging in)
It looks like the XP bar that I've left at it's default size and position. (xp bar hidden because maxlvl on the screen, but happens also on alts that are not maxed)

Hiding / enabling it from the options doesn't change a thing.
The bar cannot be moved.

/reload removes it but it still comes back sometimes.

I'm not 100% sure but it pops when interactinf with flypath

![WoWScrnShot_042421_230542](https://user-images.githubusercontent.com/76648075/116053438-fb767f00-a67a-11eb-965f-4d0923b83f17.jpg)

**Comment by BloodyFess** [comment]
The same...

**Comment by DDCorkum** [comment]
Thanks.   I will release an update later today for Retail only.

I've actually fixed this before about a year ago, but I must have re-introduced the bug when working on Burning Crusade compatibility.  The good news is that it will be super easy to fix.
